### ISSUE TITLE
Add dependency files to repo to enable offline developing.

### ISSUE THREAD

**Issue by digi0ps** [jeremyphilemon/uniqna#54]
Right now, all the dependencies are being served from CDNs. This prevents us from developing when offline. So it would be better to have the file served from our servers itself. 

Major dependencies:

- [ ] jQuery

- [ ] Material.css

- [ ] Material 

- [ ] Scroll Reveal.js

**Comment by jeremyphilemon** [comment]
@digi0ps We can serve it locally for development, but I think it would rather be better to stick with the CDNs for serving production. How do we isolate it only for development though?

**Comment by digi0ps** [comment]
That seems good! 
We can do it through an if condition in the base template.
